hash-format = "sha256"

[[files]]
file = "config/defaultoptions/extra/config/emotecraft.json"
hash = "cca45870298122e54d988d7351a6c29f5b1df7ac1fc50062685d0934d6a9b64a"

[[files]]
file = "config/defaultoptions/extra/config/iris.properties"
hash = "fca3720ec82fa4567e45e32cee4746760ae6ab85f502faf0eee9028d2e022c08"

[[files]]
file = "config/defaultoptions/extra/config/sodium-options.json"
hash = "91a06a029c227b0aa592fec98880dd4a50f582204ce49f605dabdeb69b19d2c8"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "ad65d85ee3bb4cb3c0604659af124ea289bde8f1c4c05641bace5ef65d60dda8"

[[files]]
file = "config/defaultoptions/options.txt"
hash = "5f70097ac1a9b624b1abfa9defab96e4b75723a3e309e45f29261c8a3634e43f"

[[files]]
file = "emotes/Sit.emotecraft"
hash = "264ac557957621b78835714574762648c5f5e553011b8181cad382f9afc66505"

[[files]]
file = "mods/accessories-compat-layer.pw.toml"
hash = "9f3abbba0805d021f4fec52693732de1c098ab6049f6065b9be494e9c339eeee"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "5b786ab7a57e37ec4b8f888157f79608e871653fc4b6a8cba0296690fe863704"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "833fe74ca806f98e6d0da2fbc413e229f1328c47b9b65485cfd653235383467c"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "fb413ba504cfaae8ab4d96ede3944b8eb15fa4238ae02b4331bdad2549876f2e"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "9a9d6bf3715b20cbf83b967e4dd8b77972d1256e52a7b1c2bbfa4122f5acc931"
metafile = true

[[files]]
file = "mods/azurelib.pw.toml"
hash = "92cb46fd4666ac728469801913aacb13ae7896f603be290476ebd23f1997f54a"
metafile = true

[[files]]
file = "mods/baguettelib.pw.toml"
hash = "e14620be14ef5e546335a8f865ecaf807af1b23357ef028b597118062cafa9e3"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "5ea9fb9ea7bf0fed99866d9dc20ffc907c6f6cf203dddeca9dda01ee475cfc37"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "93c4acd165a291c6d1e69c27b05b2747afc926b38a414712263fbc95f42da323"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "4925021964dc745510d669181aa79614363618950f0a597e30447602a555c05e"
metafile = true

[[files]]
file = "mods/blockui.pw.toml"
hash = "64a7bbf0eaf41a1b4d0270ec4255554a25ac278f04f0ae9e110050b42464370f"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "f33a4720ef4f315b6d1f778039e9f7bdb8f5ef1b58a57d565c30fd1d8adee207"
metafile = true

[[files]]
file = "mods/butchery.pw.toml"
hash = "cab6f98c8091c78af0fa232849303b7ce31afab5210fd85ab08f94e7163d8786"
metafile = true

[[files]]
file = "mods/camera-mod.pw.toml"
hash = "fd8400c730eed14672714c57ce51f76e90caa472c3c3d6148f60a5b0de632f30"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "24c6c3fe917ffbcef04e788dec3e003d0ed03433bc00f9cf4f23fe9b85636aa7"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "68cc51e721e993a8b7a2cbaf45369933b22b07a9c82327ab14757ee10684aa81"
metafile = true

[[files]]
file = "mods/chunkyborder.pw.toml"
hash = "a850e8ecd6c32480b8369db9823af1ac200e62a8662b43c58ebb740cdac66387"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "c7f15ebcab95f04c71940715f09ced4caad2775a91ef34389431f91bc1c7be71"
metafile = true

[[files]]
file = "mods/corpse-x-curios-api-compat.pw.toml"
hash = "e438cfd073519192f12ea88c46faa333be0bc8f99b6d26abb70bbfaae8ad4961"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
hash = "8e671fbd3a5460a61073cced391ec08efc6b67d765e49015eea45a1f1db159a0"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "36fe638633083667b1fd66b53fd1e0d76467dec3a58062fede8207350bd6771d"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "79163e41833369161b34e0d8f734c98bf6a28264c002021c0037802afb0384c8"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "bd005d9f92131c7c4a88a081aa5368c482eec2cb410d14ab245a2f081e9e1ffb"
metafile = true

[[files]]
file = "mods/deimos.pw.toml"
hash = "3ff70efee535e927d1543fce5820d84e0525018e55c30c6e9edf6759da9a5fef"
metafile = true

[[files]]
file = "mods/display-delight.pw.toml"
hash = "28f531c7efc9e5257235adcb19913ed278f3bc76a36326f28d9fb9303df9e4de"
metafile = true

[[files]]
file = "mods/domum-ornamentum.pw.toml"
hash = "560677900d746ef9c35cb48d1e51dfc8abcc188b3d390fde1dc3458f9c800057"
metafile = true

[[files]]
file = "mods/easy-npc.pw.toml"
hash = "66563f396d03ea133ec26837a6643a20d4e819999f79330e63ab810b56a47933"
metafile = true

[[files]]
file = "mods/emotecraft.pw.toml"
hash = "ee66efb9eae03c2f060086e26c9d9e4a9fbece4cd1f8fc92dfbf2771f3bad296"
metafile = true

[[files]]
file = "mods/enders-delight.pw.toml"
hash = "a693f3ca25b4b4ece785887d5a095abb1ab959804fbf6c89f119100f1de1df4b"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "6b5fa0d3a684cf6cf33f1399c2b4bdbee34dbe362548808315b488ac172e2ada"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "3443f52ef7c1f80ae1cedf459b23c38ac78dbe547cf2cc047e62d0cb2331c808"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "f48d8d1f04f68dc8e6cac4ed4768790fa7ab35ee23c2aaed5391d862c6043eab"
metafile = true

[[files]]
file = "mods/expanded-delight.pw.toml"
hash = "efce3d2641cbf0963e2b43d37f68839cca9727bcd9455998ee82a5a18d679058"
metafile = true

[[files]]
file = "mods/fallingleavesforge.pw.toml"
hash = "e5125f8f2709fd20f8182fade3d7f9e7129872c63f042c5489c6eba4733b6b49"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "7d61ad815f97afb27f7e97475e80376aa19fecf25a1b04a500a4c3a6e5055973"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "44abae510395f12f9ea97b8296b2f72e25f18b9f3f2cc0ee42c0d9afd73fe0b3"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "2741b6724a6c7d625c1c9e647a8d20ab89cd4a3975c18706da30771754c00510"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d49f83a16866886af12714660a593089291540e94aa81db2c5f849790aa0b0a8"
metafile = true

[[files]]
file = "mods/framedblocks.pw.toml"
hash = "939c71e9b7d893e65560ada8a5b7ad0c8f000db400ddbec814e038d2a2cb99c0"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "960fb33c17aca9c635f99009c1f16d75c312d043e302a599f6ce8040452079e6"
metafile = true

[[files]]
file = "mods/gigeresque.pw.toml"
hash = "29b7e184783ef77517e99d665be2d14332491bea31dfca96c6dbc1f761598e27"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "dbd756dd9bb17e6ecebcf2d7052a67a2da1c7dd378bc2089bc154916080fe031"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "0004feab868f7b873c12db05aae0d0dac6c87b497490b48bb66480e7c8d0f340"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6bdf101d3d5ec8729a8095d5853f80eb925a47c889cd10de6704b20cc7f3c73e"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "67456458bd27dd28509712b1d257f985ccc93003351c0bc4c23ebc9845a241a3"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "8cd8400cb4e2c5ba60c8a359a7b6ff501078d2056eab0aba7f6b0ac77b7a0694"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/jadecolonies.pw.toml"
hash = "94f69e149cc3604cb09197de52e6d07731d56cca3d10388ccb9dbfe8b36ee76e"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "635e0d0eba66fcc6eb94026dfa562742d5b6aa96b8f316d0ed1b1678049b54b0"
metafile = true

[[files]]
file = "mods/just-enough-effect-descriptions-jeed.pw.toml"
hash = "f5bb9b1ca3fbd24d74b4b624f5609b7902660abacd35e88e9264894d8177722a"
metafile = true

[[files]]
file = "mods/just-enough-professions-jep.pw.toml"
hash = "ead018f3794f086abf4acb238c2f99abf465fc27f002483083ba5809e02afa54"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "7905c08f37d8ebde50a5330a7dd10029de6259b0cb8adbde1170d93ea20218a7"
metafile = true

[[files]]
file = "mods/kroia_banksystem.pw.toml"
hash = "34efd64966bd1b464f1dce8cfae67ba04d1d7ee9f80c7f29ce667b5159574c40"
metafile = true

[[files]]
file = "mods/living-things.pw.toml"
hash = "2731180e4a718e4613f11268b93e34915b58faa1233eda439247f9a23f91eaf8"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "28cd260c71c34d01f59ea210af1031e94d98b4d6bd72d5a153955ce754c9a76f"
metafile = true

[[files]]
file = "mods/man-of-many-planes.pw.toml"
hash = "d887c005b64a36e1ab515d2fc6a35531b665ff7f4964b7068a01d3a136925641"
metafile = true

[[files]]
file = "mods/map-atlases-forge.pw.toml"
hash = "35060e4af7f66f5eac84b4b8be30bbe3d7b5e1e6c1c598b129bb8bc33e2d5aaa"
metafile = true

[[files]]
file = "mods/minecolonies.pw.toml"
hash = "283b72bfdfc930d2d8b7e4d65f6a5313279c43e1316daebc2e78d6a3b3e56edf"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "eae3c14c915400de36bf547550f630de727bbf48ae0ce719b99b2ff50ceaab0d"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "6f978589d682f22a6a9e62a08964400b8a1649cdf6e2b86c6bc6fe2cb01fd5ba"
metafile = true

[[files]]
file = "mods/more-music-discs.pw.toml"
hash = "97c6f557317561ec4666df0fbbe6043832368cab6ee2de346e48b7579c9a170e"
metafile = true

[[files]]
file = "mods/multi-piston.pw.toml"
hash = "bc9449306cb2c32f16347779291d68e5fba67f85d7aca04b4b9cc1c033ec4083"
metafile = true

[[files]]
file = "mods/my-nethers-delight.pw.toml"
hash = "2f6c9613ab64a27f2ba7ab55ed6d7557ffd06dff2d9db7a7e92b2d526e96a466"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "46831c04077a06df823bcd0f254833a90a9a9ccc78f5069f4b4c27fa301ac0cf"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "04ba8a8c91a6c25c42321493a2d233762bb01169fac5fd834e434887cdbf8596"
metafile = true

[[files]]
file = "mods/playerrevive.pw.toml"
hash = "f4cb8f77c11deda2facac225c4cadd3833b80bee6fb4fe92cb1638c66f9f998e"
metafile = true

[[files]]
file = "mods/prometheus-exporter.pw.toml"
hash = "2356d493ae2ab9cd519462f9394de539b216d36a782d5433e65e929ea7927947"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "c0b066684294c33972d562e0cb08ea17b2d31bcf86cd1d6c63b8e968f0eac7a2"
metafile = true

[[files]]
file = "mods/security-craft.pw.toml"
hash = "143324f103b28e6f799e808ce1ff20eab1aea7485be406c3ff95d7f007920e84"
metafile = true

[[files]]
file = "mods/simple-hats.pw.toml"
hash = "e49e5bbd1acba6a50c445e3d087552bc134e3559eae8a29da2332b4d11588228"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "82fa5e74cae0b3f0199f9822f62a976da2dc6ee03deb543d537ce55d36b11fcb"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a1fb713df668ed21dda0602e99cb23b991c8faff841e130d7aae46258c3d6a45"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "a2028f1fdc803760a29877b07b2958cecdc6402eb946f9d5a0fff9fe72b8671d"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "8ed3c58f23d9255343a590b90e1216ac58142b920c9bffdd14c7fdc32e3ee002"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "55c8056ba1454acf25252ec1c7d3a33bb59c9bd8273f28f6e0402e542073ce16"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "258a77de0a6db4c9ab045cbb240bcf4eac0dbbca3f6bc981fb461e55c247f23f"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "5995decc8738d7ddccec218dfa1ed95db9eca5bb64c98fd2cede8bf9bbc837c2"
metafile = true

[[files]]
file = "mods/structurize.pw.toml"
hash = "74462a8ec96862c081ca1860108bf021b29d3a4df7b6797062914586975e24a5"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "2e4c8891ec22ca246b414728493ff52fe177bc9c4369ed23a5a80e8332e79c67"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "15962183bec2468058c70e87aa32e902a08489b0f86741088cdc9aa958ba4931"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "539ade06248a343e6986c76c4bd88fb3d22517185bb19d768600fe51417a3255"
metafile = true

[[files]]
file = "mods/towntalk.pw.toml"
hash = "a7074e8e499d34f5ce633dbd33f818e376dd1941ec5b1d97a33acd019df69b5a"
metafile = true

[[files]]
file = "mods/waterframes.pw.toml"
hash = "a255c29cb611f60aaad313b223bc424721be5998673002da6b589b2862912621"
metafile = true

[[files]]
file = "mods/watermedia.pw.toml"
hash = "03a442894e03f9ebe0657ea717a01ea53718ac785a3b20bdcab647e5198902ee"
metafile = true

[[files]]
file = "mods/watervision.pw.toml"
hash = "393310e8c75c51eb3143c8ddcdac51917a5d759d428e5b962e4c2b4c8e87bc0e"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "735bae0e4736022f33f59f85fae837549d19992b387fe38d92af613bbe101eea"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "08d4775f8546564ad812b09062633ffc48f44b76328efe3832c021651af86b14"
metafile = true

[[files]]
file = "mods/worldeditcui-forge.pw.toml"
hash = "ae02d2d72605503d7b19c949f42bd59a1fef189c574b697907f3e303750a03c9"
metafile = true

[[files]]
file = "mods/yawp.pw.toml"
hash = "c65c117a079ac7d49c0bbc51f1fcf6c238e6e86aaaefbe45c89b6d541c82c2fb"
metafile = true

[[files]]
file = "resourcepacks/faithful-32x.pw.toml"
hash = "e633be20ba2ba87e06d9abad5c8ba066465af8f69a7bd902b5fec1dc21ea3643"
metafile = true

[[files]]
file = "resourcepacks/faithful-64x.pw.toml"
hash = "f4a9a98cd10ccd11d790e1c264ae2b4110f38f9a7464517d1eb4eea01701c455"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "bf6bf356ece200c132c604c1cdd981c8a7baf6a30ed05fa057fdfc0444df779d"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true
