hash-format = "sha256"

[[files]]
file = "config/defaultoptions/extra/config/emotecraft.json"
hash = "cca45870298122e54d988d7351a6c29f5b1df7ac1fc50062685d0934d6a9b64a"

[[files]]
file = "config/defaultoptions/extra/config/iris.properties"
hash = "fca3720ec82fa4567e45e32cee4746760ae6ab85f502faf0eee9028d2e022c08"

[[files]]
file = "config/defaultoptions/extra/config/sodium-options.json"
hash = "91a06a029c227b0aa592fec98880dd4a50f582204ce49f605dabdeb69b19d2c8"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "ad65d85ee3bb4cb3c0604659af124ea289bde8f1c4c05641bace5ef65d60dda8"

[[files]]
file = "config/defaultoptions/options.txt"
hash = "5f70097ac1a9b624b1abfa9defab96e4b75723a3e309e45f29261c8a3634e43f"

[[files]]
file = "emotes/Sit.emotecraft"
hash = "264ac557957621b78835714574762648c5f5e553011b8181cad382f9afc66505"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "833fe74ca806f98e6d0da2fbc413e229f1328c47b9b65485cfd653235383467c"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/azurelib.pw.toml"
hash = "92cb46fd4666ac728469801913aacb13ae7896f603be290476ebd23f1997f54a"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "5ea9fb9ea7bf0fed99866d9dc20ffc907c6f6cf203dddeca9dda01ee475cfc37"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "93c4acd165a291c6d1e69c27b05b2747afc926b38a414712263fbc95f42da323"
metafile = true

[[files]]
file = "mods/blockui.pw.toml"
hash = "64a7bbf0eaf41a1b4d0270ec4255554a25ac278f04f0ae9e110050b42464370f"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "f33a4720ef4f315b6d1f778039e9f7bdb8f5ef1b58a57d565c30fd1d8adee207"
metafile = true

[[files]]
file = "mods/butchery.pw.toml"
hash = "cab6f98c8091c78af0fa232849303b7ce31afab5210fd85ab08f94e7163d8786"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "68cc51e721e993a8b7a2cbaf45369933b22b07a9c82327ab14757ee10684aa81"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "c7f15ebcab95f04c71940715f09ced4caad2775a91ef34389431f91bc1c7be71"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
hash = "8e671fbd3a5460a61073cced391ec08efc6b67d765e49015eea45a1f1db159a0"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "36fe638633083667b1fd66b53fd1e0d76467dec3a58062fede8207350bd6771d"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "bd005d9f92131c7c4a88a081aa5368c482eec2cb410d14ab245a2f081e9e1ffb"
metafile = true

[[files]]
file = "mods/domum-ornamentum.pw.toml"
hash = "560677900d746ef9c35cb48d1e51dfc8abcc188b3d390fde1dc3458f9c800057"
metafile = true

[[files]]
file = "mods/emotecraft.pw.toml"
hash = "ee66efb9eae03c2f060086e26c9d9e4a9fbece4cd1f8fc92dfbf2771f3bad296"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "6b5fa0d3a684cf6cf33f1399c2b4bdbee34dbe362548808315b488ac172e2ada"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "f48d8d1f04f68dc8e6cac4ed4768790fa7ab35ee23c2aaed5391d862c6043eab"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d49f83a16866886af12714660a593089291540e94aa81db2c5f849790aa0b0a8"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "960fb33c17aca9c635f99009c1f16d75c312d043e302a599f6ce8040452079e6"
metafile = true

[[files]]
file = "mods/gigeresque.pw.toml"
hash = "29b7e184783ef77517e99d665be2d14332491bea31dfca96c6dbc1f761598e27"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6bdf101d3d5ec8729a8095d5853f80eb925a47c889cd10de6704b20cc7f3c73e"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "8cd8400cb4e2c5ba60c8a359a7b6ff501078d2056eab0aba7f6b0ac77b7a0694"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/jadecolonies.pw.toml"
hash = "94f69e149cc3604cb09197de52e6d07731d56cca3d10388ccb9dbfe8b36ee76e"
metafile = true

[[files]]
file = "mods/living-things.pw.toml"
hash = "2731180e4a718e4613f11268b93e34915b58faa1233eda439247f9a23f91eaf8"
metafile = true

[[files]]
file = "mods/minecolonies.pw.toml"
hash = "283b72bfdfc930d2d8b7e4d65f6a5313279c43e1316daebc2e78d6a3b3e56edf"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "eae3c14c915400de36bf547550f630de727bbf48ae0ce719b99b2ff50ceaab0d"
metafile = true

[[files]]
file = "mods/multi-piston.pw.toml"
hash = "bc9449306cb2c32f16347779291d68e5fba67f85d7aca04b4b9cc1c033ec4083"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "04ba8a8c91a6c25c42321493a2d233762bb01169fac5fd834e434887cdbf8596"
metafile = true

[[files]]
file = "mods/playerrevive.pw.toml"
hash = "f4cb8f77c11deda2facac225c4cadd3833b80bee6fb4fe92cb1638c66f9f998e"
metafile = true

[[files]]
file = "mods/prometheus-exporter.pw.toml"
hash = "2356d493ae2ab9cd519462f9394de539b216d36a782d5433e65e929ea7927947"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "82fa5e74cae0b3f0199f9822f62a976da2dc6ee03deb543d537ce55d36b11fcb"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a1fb713df668ed21dda0602e99cb23b991c8faff841e130d7aae46258c3d6a45"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "5995decc8738d7ddccec218dfa1ed95db9eca5bb64c98fd2cede8bf9bbc837c2"
metafile = true

[[files]]
file = "mods/structurize.pw.toml"
hash = "74462a8ec96862c081ca1860108bf021b29d3a4df7b6797062914586975e24a5"
metafile = true

[[files]]
file = "mods/towntalk.pw.toml"
hash = "a7074e8e499d34f5ce633dbd33f818e376dd1941ec5b1d97a33acd019df69b5a"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "08d4775f8546564ad812b09062633ffc48f44b76328efe3832c021651af86b14"
metafile = true

[[files]]
file = "mods/worldeditcui-forge.pw.toml"
hash = "ae02d2d72605503d7b19c949f42bd59a1fef189c574b697907f3e303750a03c9"
metafile = true

[[files]]
file = "mods/yawp.pw.toml"
hash = "c65c117a079ac7d49c0bbc51f1fcf6c238e6e86aaaefbe45c89b6d541c82c2fb"
metafile = true

[[files]]
file = "resourcepacks/faithful-32x.pw.toml"
hash = "e633be20ba2ba87e06d9abad5c8ba066465af8f69a7bd902b5fec1dc21ea3643"
metafile = true

[[files]]
file = "resourcepacks/faithful-64x.pw.toml"
hash = "f4a9a98cd10ccd11d790e1c264ae2b4110f38f9a7464517d1eb4eea01701c455"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "bf6bf356ece200c132c604c1cdd981c8a7baf6a30ed05fa057fdfc0444df779d"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true
