name = "MouCraft"
author = "416C6578"
version = "1.6.2"
description = "MouCraft is a survival-RP modpack for Minecraft 1.21.1 using NeoForge."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99a3bb50e8afa50051bf6631d003fd47a645e06a38204a3fddf9c8273df296a3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = ["1.21.1"]
