name = "MouCraft"
author = "416C6578"
version = "1.4.0"
description = "MouCraft is a survival-RP modpack for Minecraft 1.21.1 using NeoForge."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b00ce95cd060b5d7c0b658acebc3f8bac48f89d25a290114c99931774040b132"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = ["1.21.1"]
