hash-format = "sha256"

[[files]]
file = "config/defaultoptions/options.txt"
hash = "ff36336f954851ae6c1210446938aad82ab08be1777e900165b3be39caf622ee"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "db29d08bcba55226602b55669b5ff21d99642c09758df93267789ce95a34bdca"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "32220d2f0275dd71f089742921c86c8964186a8d9610434f53f67f2e459c2ef2"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "5f30c1c0363dd44c10db196a8d8a7f164ff06e06b0b80234a519d9e49b2a7f84"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "ff5879f6ad48b7a48c391054e26ef4d70b96f7339bff3bec28877e0ab919f998"
metafile = true

[[files]]
file = "mods/chunky-pregenerator-forge.pw.toml"
hash = "6f3b2586044baf55d5b1cb07752c9def847208270480bf9d893c803277493c1f"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "3f47b68f174a4719ef9b099ea12732a4cb840be03635e91dd6c24515f4cf6814"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "742108414562eb148ff95c653f15731fe793a58e50ae2747017da0cf20c53982"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "0f695559cbee2bdda09f2c32095bf7317b9f3c3c7c378a9eb155bc9746fb5d8b"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "0042336abc94bae434faa534e9c2e1d1e477d5f984f9f993d92aa856143f3379"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "9389b4311f93eaea1e627ee793137607370e2e782836e03ee6ca49a41cc7b06d"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "942b02525962980b6176677cca162d27c1210b686985ad11db0055fe39d42a7d"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
hash = "bcba425c2f7a90f737f44ef05070903f5f5d683d69836bca87731b39844e329c"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "4c9abda63d99719987d4a461997f4e627256a23f6e605ebb06bc30752fae0099"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "e34877bf9d74d3f71c69fdd47ce509fa473fadcdf88f87f79754a522cfa1c60b"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "97521b85e74dfbc642b9102a46be0cdda07b9cfe36aba027a3878054f93ccfcb"
metafile = true

[[files]]
file = "mods/prometheus-exporter.pw.toml"
hash = "2356d493ae2ab9cd519462f9394de539b216d36a782d5433e65e929ea7927947"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "e5a88eeea38105e024dc8c8849e28d90af25cec68f1d0f6716796fe9746bddd2"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "03d264a85c6b6fd0f011c958caf94a3238931fdd48c5c156ddb6e13fc16ce601"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f3c75c6d415e4d68307d972ed30ced99ba05968c7ff85301154a60fc42eeed95"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "302695f3a9a8e6aca31d1108da08172b96954f37be26040cce16716f860cd0eb"
metafile = true

[[files]]
file = "mods/yawp.pw.toml"
hash = "e9e5d68773dac69422e179e17750f59ef058cfc8d4dcb7be592256a9285e76da"
metafile = true

[[files]]
file = "resourcepacks/faithful-32x.pw.toml"
hash = "c25bbe6b2e4c86571f2a471b8331dfb3137d6713661a74bb5929072e2576c044"
metafile = true

[[files]]
file = "resourcepacks/faithful-64x.pw.toml"
hash = "c94510d4c108acb21a436bfb3f217a2f3d564361d5c154a6d5ee244d44ff3619"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "a8a5b310a327b30be69b526640abbd7f61300a0266cd1d62a8765058ad3e8dac"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "91a77a3f031bdf1ac4de9d1be6925704e85dfd8895bad7b717fc2ec1d50d9114"
metafile = true
