name = "MouCraft"
author = "416C6578"
version = "1.4.2"
description = "MouCraft is a survival-RP modpack for Minecraft 1.21.1 using NeoForge."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d79f05a6dc37c59a9987ba3e849c2571e92d8ca63953c8e85aff7b07729788b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = ["1.21.1"]
