name = "MouCraft"
author = "416C6578"
version = "1.6.0"
description = "MouCraft is a survival-RP modpack for Minecraft 1.21.1 using NeoForge."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bca6dda15ab737d1ee59a97101d271a746ef819924ca175df3b1b7ef005c6d0c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = ["1.21.1"]
