name = "MouCraft"
author = "416C6578"
version = "1.4.2"
description = "MouCraft is a survival-RP modpack for Minecraft 1.21.1 using NeoForge."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee42f0fb00c6ca0ad0346811844a8e028e3b415ee8e20265de7e3db814e57695"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = ["1.21.1"]
