name = "MouCraft"
author = "416C6578"
version = "1.6.0"
description = "MouCraft is a survival-RP modpack for Minecraft 1.21.1 using NeoForge."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89d0a4cf566e56867c8b99a9be9c840c45a7a47bf50c4ad82eb27f71c9231cdc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = ["1.21.1"]
